### PR TITLE
Bump to version 0.3.5

### PR DESCRIPTION
**Pull request by guyhamo**
# Salto Version 0.3.5

## New features
_CLI_
- Added the command `salto element rename <sourceElementId> <targetElementId>`
- Support element selectors with multiple values separated with pipes ('|')
- improve the display for a list of objects in the deploy's detailed plan.

_Netsuite adapter_
 * Add go-to-service option for new types of instance elements in Netsuite.
 * Identify references that are contained in a string value and add them as `_generated_dependencies`.
 
 _Jira adapter_
 * Added issue type to default fetch configuration.
 * Now fetching components under projects.

_Zendesk adapter_
* Sort the dynamic content item variants to avoid unneeded differences between sandboxes.

## Bug fixes
_Core_
 * Fixed issue where static files would be loaded incorrectly in workspaces with multiple environments, causing missing static files and / or incorrect deploy plans.
 * fixed issue that would cause unneeded cache invalidation and lead to slow loading times.
 * Fixed issue where static files would be loaded incorrectly in workspaces with multiple environments, causing missing static files and / or incorrect deploy plans.
 * Fixed slowness due to cache invalidation after an environment rename.
 
 _Salesforce adapter_
 * Fixed annotation type under picklist field type
 
_Jira adapter_
* Fixed issue with FieldConfiguration failing to fetch

_Zendesk adapter_
* Fix a few field types that were not marked as lists.

## User information
* _Netsuite_
	* **Default adapter configuration has changed, please run `salto workspace clean -ncrsg` to reset the configuration in your workspace.**
	* following a change some environments might trigger a one time notification due to the addition of `_generaeted_dependencies` annotation.
* _Salesforce_
	* The Salesforce picklist type definition will change the next time a fetch is done on a salesforce workspace
* _Zendesk_
	* Changes in `dynamic_content_item` instances (under the `variants` field)

### CODE REVIEW

**Comment by guyhamo** [comment]
### What's New in Version 0.3.5

**What's New**
 * Added the command `salto element rename <sourceElementId> <targetElementId>`
 * Support element selectors with multiple values separated with pipes ('|')
 * improve the display for a list of objects in the deploy's detailed plan.
  
_Netsuite adapter_
 * Add go-to-service option for new types of instance elements in Netsuite.
 * Identify references that are contained in a string value and add them as `_generated_dependencies`.
 
 _Jira adapter_
 * Added issue type to default fetch configuration.
 * Now fetching components under projects.
 * **Default adapter configuration has changed, please run `salto workspace clean -ncrsg` to reset the configuration in your workspace.**

_Zendesk adapter_
* Sort the dynamic content item variants to avoid unneeded differences between sandboxes.


### Bug Fixes
---
 * rename inner references on element rename.
 * Fixed issue where static files would be loaded incorrectly in workspaces with multiple environments, causing missing static files and / or incorrect deploy plans.
 * fixed issue that would cause unneeded cache invalidation and lead to slow loading times.
 * Fixed issue where static files would be loaded incorrectly in workspaces with multiple environments, causing missing static files and / or incorrect deploy plans.
 * Fixed slowness due to cache invalidation after an environment rename.
 
 _Salesforce adapter_
 * Fixed annotation type under picklist field type
 
_Jira adapter_
* Fixed issue with FieldConfiguration failing to fetch

_Zendesk adapter_
* Fix a few field types that were not marked as lists.

### User information
* _Netsuite_
	* following a change some environments might trigger a one time notification due to the addition of `_generaeted_dependencies` annotation.
* _Salesforce_
	* The Salesforce picklist type definition will change the next time a fetch is done on a salesforce workspace
* _Zendesk_
	* Changes in `dynamic_content_item` instances (under the `variants` field)

**Comment by guyhamo** [comment]
comments about the release notes are welcome because this is my first time doing them.

**Comment by alonstern** [comment]
The template seems to be different than the one we used in the prev deployments (probably the in Notion is outdated). you can the updated one from here (https://github.com/salto-io/salto/pull/2472) 

Also `rename inner references on element rename.` is not very clear (I know you didn't write it) you can change it something like `Fixed rename to also rename inner references`

**Comment by adamro** [comment]
`rename inner references on element rename.` is actually a fix to a bug that didn't exist before this release note, so it's redundant

Also, the `Default adapter configuration has changed, please run salto workspace clean -ncrsg to reset the configuration in your workspace.` thing sounds like it should be in the "User information"

**Review by adamro — APPROVED** [review]

**Pull request merged**
