### PR TITLE
SALTO-2652 Enable deploy QuickAction with only one QuickActionLayoutColumns - quick fix

### PR DESCRIPTION
**Pull request by Uri-Bar**
quickfix of the previous PR

### CODE REVIEW

**Review by tamtamirr — APPROVED** [review]
Please change the description to `quickfix of the previous PR` and remove all of the release notes sections to avoid confusion to whoever will bump the OSS next.

Also, FYI @ori-moisis @netama this is another bug coming from outside the package

**Comment by ori-moisis** [comment]
this is going to affect other adapters as well, not sure which ones are using this function
@dantal4 @alonstern - may want to review and make sure this is not going to be a problem before we merge this

if this presents a problem in one of the other adapters we can do what we did with the rest of the PRs in this subject and pass the value only from the salesforce adapter instead of changing the default for everyone

**Comment by alonstern** [comment]
LGTM for the Jira adapter

**Comment by dantal4** [comment]
It isn't effecting NS.

**Comment by netama** [comment]
looks like this is already true in zendesk (thanks @ori-moisis for checking)

**Pull request merged**
