### PR TITLE
Bump to version 0.1.26

### PR DESCRIPTION
**Pull request by omrilit**
### What's New in Version v0.1.26

_Salesforce adapter_
 * Support MatchingRules.
 * Added more references in CPQ configuration.
 * Update CPQ configuration example.
 * Added upsert logic for Custom Object Instances on Add based on saltoIDSettings in the dataManagement configuration. Deploying Instances between environments is now "safer". It will not create logically duplicate Instances when they are already created as side effect of other Adds or already exist in the target environment.

_Netsuite adapter_
 * Expose default configuration values.
 * Use newer SuiteCloud Development Framework version.

_Visual Studio Code extension_
 * Support symbol search on fields.

### Upgrading from v0.1.25
If you have an existing workspace with NetSuite service, you should create a new workspace and add NetSuite service to it. This will download the new SuiteCloud Development Framework version.
Once the service is added, you can remove the new workspace and continue to work on your old one.
The `salto` commands that has to be done to create workspace with NetSuite service are:
```
salto init
salto services add netsuite --nologin
```

### CODE REVIEW

**Comment by omrilit** [comment]
**The description is based on the following commits:**
* 7cd68056 : Netsuite: use default values for config to present them in config nacl (#1396)
* 606fd54b : Netsuite: upgrade sdf version that uses jar version 2020.1.1 (#1394)
* 61fbecc6 : SALTO-806 Added a method to ListType to be used for setting ListTypes annotations (#1389)
* 93683074 : SALTO-806 Nested metadata types update (#1364)
* cc23a3f0 : support symbol search on fields (#1379)
* dca9f34e : SALTO 925 [Partial] - Add CPQ LookupObject valueSet references (#1390)
* 9297d6e3 : Update CPQ default configuration according to new learnings (#1388)
* 947c7881 : Add CPQ instance references to CustomObject (#1386)
* 3ce3f384 : Custom object instances upsert (#1354)

**The below commits are not documented in the release notes:**
* 0145fdb0 : Change move to 2 commands: move-to-common & move-to-envs (#1373)
* 5175b7bc : changed default route to route nested additions to common if all of t… (#1369)
* 4210bb14 : SALTO-937: Add error in the case of no existing adapter when calling getAdapters… (#1372)
* a7b7f954 : Handle single element in valueSet - fetch as list (#1385)
* 2c6ac47a : Fixed hubspot validateCredentials (#1384)
* f5e7b8dc : Extend in memory state implementation to support the full State interface (#1381)
* 393c98ff : added full command and runtime log (SALTO-920) (#1382)
* 5b1c4a13 : fixed workspace methods that use the nacl file source fail after current env is changed (SALTO-927)
* e330b6b8 : Add function to apply transform on change data (#1378)
* 1e0ae3d8 : Log adapter config values upon fetch & deploy (#1395)
* 5922a7e3 : Add dir-based isEmpty check (#1392)
* 0bfe1f04 : Fix typo of an error string in salesforce adapter creator (#1383)
* efd14a4f : align doc with new move-to-common and move-to-envs commands (#1377)
* 9d9b93b1 : Netsuite: remove vm2 hacks after removing its usages in SDF (#1370)
* ff8fc58f : add missing newline (#1375)
* 87e4e571 : fixed typo in docs (#1376)

**Comment by ori-moisis** [comment]
will running `salto service add netsuite --nologin` be sufficient?
a little easier than having to get credentials for netsuite just to fix the upgrade

**Comment by ori-moisis** [comment]
I think `Update CPQ default configuration.` => `Update CPQ configuration example.`
@adamro , is that correct?

**Review by ori-moisis — APPROVED** [review]

**Comment by omrilit** [comment]
Applied @ori-moisis comments

**Pull request merged**
