### PR TITLE
SALTO-2864 - Salesforce: Allow creating fields of type 'Address'

### PR DESCRIPTION
**Pull request by tomsellek**
Don't trigger the change validator if a field is created of type 'Address'.

---

SalesForce [supports custom Address fields](https://help.salesforce.com/s/articleView?id=sf.fields_caf.htm&type=5), and so should we.

---
_Release Notes_: 
SalesForce: fields of type 'Address' will no longer cause a warning during deploy

---
_User Notifications_: 
N/A

### CODE REVIEW

**Review by yuribro — APPROVED** [review]
LGTM! 
Did you test it both with deploy & fetch?

**Comment by tomsellek** [comment]
> Did you test it both with deploy & fetch?
@yuribro I'm actually not sure how to do that - I see fields of type `salesforce.Address` in my NaCl files, but I don't get any warnings when I deploy (even with the code from main)

**Comment by yuribro** [comment]
> > Did you test it both with deploy & fetch?
> > @yuribro I'm actually not sure how to do that - I see fields of type `salesforce.Address` in my NaCl files, but I don't get any warnings when I deploy (even with the code from main)

Are these elements in the deploy plan? Try editing them or create a new type with that field

**Comment by tomsellek** [comment]
Before change:
image
After change:
image

**Pull request merged**
