### PR TITLE
SALTO-1854: Rename ChangeElement to ChangeData

### PR DESCRIPTION
**Pull request by EllaSharakanski**
Deprecated and created a new name for:
* `getChangeElement` --> `getChangeData`
* `getAllChangeElements` --> `getAllChangeData`

The idea is that those functions accept a `Change`, which can also be a `DetailedChange`, in which case the data won't necessarily be an element.

---

I'm not sure if I should also rename `restoreChangeElement`, `resolveChangeElement`, and `isEmptyChangeElement`.
They will accept a `DetailedChange` because `Value` is `any`, but as far as I understand their functionality won't make sense. Not sure.

---
_Release Notes_: 
* API: Deprecated `getChangeElement` in favor of `getChangeData` and `getAllChangeElements` in favor of `getAllChangeData`

### CODE REVIEW

**Comment by ori-moisis** [comment]
generally looks good to me
a few of things
1. we need to figure out how to ensure people don't write new code with `getChangeElement`, maybe a lint rule to disallow it?
2. we need to figure out when we remove `getChangeElement` from the codebase and who does that, we would probably want to do that ASAP, maybe open a ticket and assign a specific date an owner to it?
3. Maybe we should also add a runtime warning log for using a deprecated function name to help external developers with migrating their code to the proper API?

Also, not approving right now because I'd like more people to be aware of this before we make this api change.
specifically FYI @adamro @roironn @netama, if you have any comments on this change...

**Comment by EllaSharakanski** [comment]
1. I don't really understand the difference between having a lint rule to disallow using the old code, and deleting the old code (resulting in a build error). I thought the idea is to just allow using the old name so that we can have a clean bump PR that does not change anything. A separate SaaS PR will change all the usages. Then, there will be an OSS PR to delete the deprecated functions. Lastly, another SaaS bump. You are right that if at this point, before the last SaaS bump, someone will use the deprecated version, then we won't be able to have a clean bump again. However, it doesn't matter as much - we will get a build error after the bump and just won't have a 100% clean bump. Also, I added the @deprecated comment and it makes vscode have a strike-through so I doubt that people will use the method.
2. I thought I will do that right after the bump PR and the "use the new name" PR. I thought I would use the same ticket, do you think I shouldn't?
3. Is there a way to do that?

**Comment by ori-moisis** [comment]
1. sure, deleting the old code is the end state, but until then I wanted to make sure people won't write new code with the old function names. if the deprecation comment warns everywhere in the code, that is probably good enough...
2. I think we might want to have at least one OSS release with both function names to allow a smooth transition for all the code that might depend on our API . we could technically break the API without warning since we are still v0, but that isn't a very nice thing to do...
3. technically, `getChangeElement` is still a function, so...
```typescript
const getChangeElement = <T>(change: Change<T>): T => {
  log.warn(...)
  return getChangeData(change)
}
```

**Comment by EllaSharakanski** [comment]
1. This is what it would look like:
Screen Shot 2022-01-02 at 16 59 52
As far as I understand having a lint error is still a breaking change if your pipeline depends on having no lint errors, no?
2. Is this really something we have ever done? Meaning, do we have any "minimize breaking changes" policy? Also, if so, we should have a way to notify users about those changes in the release notes. Where do I write about this?
3. That's very manual! Have we ever done this? Do we have a format? I think we should have a format because this is user-facing

**Review by ori-moisis — APPROVED** [review]
I don't want to delay this too much (seems like it is already starting to accumulate conflicts)
ideally I would have liked to do this is stages to allow our external interface to be at least a little usable, but if we don't agree about this I think at this point it is not important enough (there isn't enough external usage to justify the argument).
worst case, after this is merged I'll post a message on the external slack so at least the users there will be notified about it and know what to do

**Comment by EllaSharakanski** [comment]
I agree waiting for a release makes sense, just not sure where I write notes to notify clients about this change in a new release.

**Comment by ori-moisis** [comment]
so far we've been treating the release notes as something facing a "cli user", but maybe in this case we can make an exception (until we create a better methodology around it) and put the "api user" notification in the release notes as well?

**Comment by EllaSharakanski** [comment]
Okay :)

**Pull request merged**
