### PR TITLE
Salesforce: add onPreDeploy filter option

### PR DESCRIPTION
**Pull request by omrilit**

### CODE REVIEW

**Comment by ori-moisis** [comment]
Something that bothers me with this design:
`preDeploy` has a very different effect than the other "callbacks" in filters - it tries to appear the same by passing in an element and returning void, thus signaling that, like the other callbacks, it is supposed to edit an element in place, but in fact it only works for instances, is only allowed to change the values and all of its effects are discarded. it feels like the interface is misleading.
This creates a lack of symmetry between `onFetch` and `preDeploy` which I think will hurt us in the long term if we try to expand the use of this mechanism (like the refactor of profiles that gets suggested from time to time)


There is also something strange about `preDeploy` being in a filter but not getting called before every deploy but only for certain types. with the current implementation you can have a `preDeploy` filter for Aura components, but not for Layouts or Profiles.

**Comment by omrilit** [comment]
As I see it I think that I can modify the preDeploy signature to return a new element(instance?) or undefined. This will resolve the misleading side effect it does. It named preDeploy while 'deploy' stands for the `client.deploy` and not `adapter.deploy` and thus Profiles & Layouts do not pass through it.

Maybe having the preDeploy hook is just overkill for the intention I created it for and I should only use a transform method before calling to deploy, without having a filter option for it (as I don't use client or any other context).
This is what @adamro votes for. @ori-moisis WDYT?

**Comment by ori-moisis** [comment]
I think I agree with @adamro 
I do think we will need to generalize it at some point, but maybe it doesn't have to be now

**Comment by omrilit** [comment]
Closing this one, the solution is at https://github.com/salto-io/salto/pull/1278/commits

**Pull request closed without merging**
