### PR TITLE
SALTO-4738 - Salesforce: update CPQ README

### PR DESCRIPTION
**Pull request by tomsellek**
Make the CPQ example config be the same as the default CPQ config we actually generate

---

---
_Release Notes_: 
N/A

---
_User Notifications_: 
N/A

### CODE REVIEW

**Comment by adamro** [comment]
Are we sure about replacing and not having both in our OSS docs?

**Comment by tomsellek** [comment]
> Are we sure about replacing and not having both in our OSS docs?

@amitgoldarb ?

**Comment by amitgoldarb** [comment]
@adamro @tomsellek we can have both. I think it makes sense to place the newer internalId based one on top though and make clear this is the suggested configuration.

**Comment by tomsellek** [comment]
Closing. @amitgoldarb will handle this.

**Pull request closed without merging**
