### PR TITLE
salto-3441 add SuiteQL max result size support

### PR DESCRIPTION
**Pull request by kami-delaroz**
add MAX_SUPPORTED_RESULT_SIZE to support queries in SuiteQL only for result size that is not exceeding max-size

---

_None_

---
_Release Notes_: 
In case we try to fetch results that are exceeding MAX_SUPPORTED_RESULT_SIZE, no data will be handled.
This case might happen when trying to fetch system notes, and there were too many changes since last fetch. 
we'll skip this fetch, hence loose information regarding the ChangedBy and ChangedAt.

---
_User Notifications_: 
_None_

### CODE REVIEW

**Review by omrilit — COMMENTED** [review]
Looks great!
I wonder whether we should allow us/the user to control this value dynamically via the adapter config but I tend to think that we won't really use that value so I am fine with having it hard coded for now.

In addition, as I said also in the ticket, I think that we should "Emit an event log indicating it occurred".
Currently we only have this indication in the logs which is not exposed to the SaaS users.
If we'll return a `SaltoError` as part of the `FetchResult`, the SaaS will create a dedicated `eventLog` (https://github.com/salto-io/salto_private/blob/master/packages/ws-operations/src/wslc/operations/fetch/executor/index.ts#L187) which will be visible to the user.

**Comment by omrilit** [comment]
I think that the Release Notes should be a bit more self explained and detail the effect on the user, i.e. lost information regarding the ChangedBy & ChangedAt.

**Comment by ori-moisis** [comment]
no activity here for a while, @omrilit @kami-delaroz can we close this?

**Comment by ori-moisis** [comment]
> no activity here for a while, @omrilit @kami-delaroz can we close this?

one more round - @omrilit @kami-delaroz, can we close this?

**Comment by omrilit** [comment]
> @dantal4 do you think that all of the queries improvements that we perform may change our mind here and we'll want to try and query all the data and not limit it?

@dantal4 back to you,

**Comment by dantal4** [comment]
> @dantal4 do you think that all of the queries improvements that we perform may change our mind here and we'll want to try and query all the data and not limit it?

@kami-delaroz @omrilit we didn't experience timeouts there lately, right? Maybe we can leave it for now.

**Comment by ori-moisis** [comment]
closing based on the last comment
feel free to open a new one if it becomes relevant

**Pull request closed without merging**
