### PR TITLE
SALTO-4177: Remove layouts

### PR DESCRIPTION
**Pull request by IdoZakk**
The previous try was not enough
---

None

---
_Release Notes_: 
Jira Adapter:
* Removing Issue Layouts

---
_User Notifications_: 
None

### CODE REVIEW

**Comment by alonstern** [comment]
Can we check if it is in the supported types in the beginning of the filter instead so we will be able to add it for specific users?

**Comment by IdoZakk** [comment]
We removed it from the supported types, so we cannot add it now (it became un-recognized...)

**Comment by IdoZakk** [comment]
I added it as a config flag now (default off), so we will be able to turn it on for customers

**Review by alonstern — APPROVED** [review]

**Comment by alonstern** [comment]
> We removed it from the supported types, so we cannot add it now (it became un-recognized...)

I meant that we will be able to add it back by overriding the supported types in the user's adapter config, but this will work too

**Pull request merged**
