### PR TITLE
Salesforce: remove & add XML_ATTRIBUTE_PREFIX upon fetch & deploy

### PR DESCRIPTION
**Pull request by omrilit**

### CODE REVIEW

**Comment by ori-moisis** [comment]
with the current design it seems like one direction of handling xml attributes is done in a filter and uses one logic (anything that somehow includes "attr_" gets changed) and the other direction is in the xml_transformer and uses a different logic (annotation of the field).

feels not right to me to have the remove direction completely decoupled from the add direction, using a different logic feels like it could lead to bugs in some cases

**Comment by omrilit** [comment]
Upon fetch, I intentionally simplified the removal of the `attr_` from attributes keys assuming that there is no such key in SF (there are no `_` in SF keys).
If you think that we should have the same methodology of checking the `IS_ATTRIBUTE` annotation I can definitely do it, just thought that it's redundant here.

**Comment by ori-moisis** [comment]
I care less about the specific implementation, either we encounter the case where it is a bug and we'll handle it then or we won't and nobody will care about a theoretical bug.
the thing I am more worried about is the fact that one feature has two parts that are highly coupled in terms of making things work (neither transform direction will work without the other) but are very much decoupled in the code (different files, different mechanisms, different layers of the adapter).
but I also feel like I am the only one that cares about it and am putting too much effort into trying to maintain something that nobody else actually needs and is already somewhat broken (symmetry in the adapter), so if you think the current design is better you can just say so and I will approve the PR

**Comment by omrilit** [comment]
I agree with you regarding the symmetry and thus my first approach was to create a dedicated filter for onPreDeploy. After consulting with @adamro I realised that there are many places that this symmetry is already broken, e.g. references creation and resolving. And since the onPreDeploy differs from all other filter options, I was convinced that we shouldn't it.

Regarding the potential bug, I really think that it's just theoretical and thus I chose to implement it that way in first place.

**Comment by ori-moisis** [comment]
I am not sure I understand the bottom line from your comment...
is this the design you think is best for this feature and we should keep it decoupled?

**Comment by omrilit** [comment]
@ori-moisis yes

**Pull request merged**
