### PR TITLE
Bump to version 0.1.22

### PR DESCRIPTION
**Pull request by omrilit**
### What's New in Version v0.1.22

_Salesforce adapter_
 * Improve deploy performance for CustomObject Instances.
 * Modify dataManagement config:
    * Support regular expressions for includeObjects, excludeObjects and allowReferenceTo.
 	* Remove includeNamespaces list.

_Netsuite adapter_
 * Update types definitions.

_Visual Studio Code extension_
 * Don't display warnings if errors exist.

### Bug Fixes
 * Avoid printing values upon workspace validations to prevent too long output.
 * Fix Salesforce deploy changes on SocialCustomerServiceSettings that occurred immediately after fetch.

### Upgrading from v0.1.21
 If you had an enabled dataManagement in Salesforce adapter configuration:
 * For each "OLD_VALUE" value in includeNamespaces, add "^OLD_VALUE__.*" to includeObjects list.
 * Remove the includeNamespaces key and its values from the dataManagement config file.

### CODE REVIEW

**Comment by omrilit** [comment]
**The description is based on the following commits:**

* e08c43dd : dataManagement config by regex and not full string match (#1304)
* 36dd256b : CustomObject Instances deploy groupings (#1292)
* 3433428d : Do not print values upon workspace validations (#1293)
* e517cb1a : Netsuite: regenerated 2020.1 api version types
* 6c9d6080 : Netsuite: fix form types fields order


**The below commits are not documented in the release notes:**

* fa23c1d6 : SALTO-873 Add accept-suggestions / y cmdline argument (#1303)
* 1900492e : SALTO-875 - add copy command for duplicating elements across environments (#1295)
* 5b270cfb : SALTO-883 Add fetch mode suggestion for multienv (#1294)
* 78818ee5 : SALTO-873 Multienv - suggest to isolate the existing env when adding a 2nd env (#1288)
* 4f6a9905 : SALTO-793: store relevant information in type annotations on fetch (#1298)
* 710f0002 : Fix restore bug on deploy in salesforce (#1307)
* 6f70ec40 : Netsuite: Do not fail in e2e when having config changes due to SDF fetch issue (#1305)
* d91fcea2 : improve test readability (#1299)
* 04c92128 : fix typos (#1302)
* 6b60bc5d : remove unused file
* fb22de0f : limit number of workers to avoid out of memory in CI
* f8c321f2 : export getDefaultAdapterConfig (#1297)
* 3674e706 : Netsuite: E2E infra with one simple test, after adding manually accounts to the creds pool. SALTO-826 (#1236)
* d46e5952 : minor refactor to dag (#1296)
* 95e7caa1 : remove explicit `exists` check (#1300)
* 344f4397 : Move the resolve and restore values in deploy to be at the start and … (#1283)
* f9cea543 : do not display warnings if errors exist (#1287)
* 6424f693 : fixed some minor language issues in the text help for promote/demote + moved the text help for diff to be last (#1301)

**Comment by ori-moisis** [comment]
#1287 should be in the release notes IMO - it changes user facing behavior (in the vscode extension)

**Comment by gilhoffer** [comment]
Do we want to wait for https://github.com/salto-io/salto/pull/1310 as well?

**Comment by omrilit** [comment]
> Do we want to wait for #1310 as well?

Yes, @ori-moisis asked me f2f to wait for it as well, thanks.

**Pull request merged**
